title: Blog Bibliotheks- und Archivinformatik Sloth-O-Nator
author: Joëlle M.
description: > # this means to ignore newlines
  Lerntagebuch im Kurs Bibliotheks- und Archivinformatik HS21 an der FHGR unter dem Pseudonym Sloth-O-Nator
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
